### ISSUE TITLE
[5.x] Meteor app kept restarting, reverting to 4.x fixed it

### ISSUE THREAD

**Issue by allaire** [phusion/passenger#1422]
Our meteor app kept restarting under load on 5.x version, giving the following errors:

```
[ 2015-03-10 10:57:45.2171 23022/7ff4917fa700 ServerKit/Server.h:892 ]: [Client 8-1117] Disconnecting client with error: client socket write error: Broken pipe (errno=32)
[ 2015-03-10 10:59:39.0778 24366/7f02ed7fa700 agents/HelperAgent/RequestHandler/CheckoutSession.cpp:236 ]: [Client 7-33] Returning HTTP 503 due to: Request queue full (configured max. size: 100)

2015/03/10 10:59:37 [error] 16194#0: *567141 connect() to unix:/tmp/passenger.ffZWbes/agents.s/server failed (11: Resource temporarily unavailable) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: name.host.com, request: "GET /sockjs/info?cb=w1n21my2gl HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.ffZWbes/agents.s/server:", host: "name.host.com", referrer: "https://name.host.com/"
```

we quickly reverted back to latest 4.x, which fixed the issue (no more errors like above). We did all the nginx config changes that were mentioned in the CHANGELOG of 5.x

**Comment by choyweston** [comment]
+1

**Comment by OnixGH** [comment]
Hi guys, thanks for reporting, which version did you use? The log suggest issue #1404 or maybe #1412, both recently resolved (5.0.3 is coming up soon).

**Comment by allaire** [comment]
We were running on 5.0.2

**Comment by FooBarWidget** [comment]
Hi @allaire and @choyweston, thanks for reporting this. [Version 5.0.4](https://blog.phusion.nl/2015/03/12/passenger-5-0-4/) has been released. I believe the bug you're reporting has been fixed, but there's also a chance that the issue you're running into is a different one. Could you give 5.0.4 a try? And if you still run into the problem, could you gather some analysis data as described below?

 1. Please save the output of `passenger-status --show=requests`.
 2. Please save the output of `passenger-status` (without the `--show=requests` part).

If it's not fixed in 5.0.4 we'll do our best to fix it for 5.0.5.

**Comment by allaire** [comment]
Will do soon, thanks for the quick response.

**Comment by FooBarWidget** [comment]
Hi @allaire, have you had a chance to test 5.0.4 yet? Do you believe the issue is fixed?

**Comment by allaire** [comment]
@FooBarWidget Not yet, everything is stable currently using latest 4.x so we're a bit "shaky" to update to 5.0.4!

**Comment by jonfer** [comment]
@FooBarWidget I also have this problem, but with a Rails app. I first tried with 5.0.2 then downgraded to 4.x and everything worked fine. I tried 5.0.4 and I still get this problem.

**Comment by FooBarWidget** [comment]
@jonfer Your Rails app keeps restarting? Can you post more information about the symptoms? What do you see in the web server error log, for example?

**Comment by jonfer** [comment]
In the nginx log I was getting the same error as him: 
> [error] 37258#0: *3896341 connect() to unix:/tmp/passenger.ZuJ6MnD/agents.s/server failed (11: Resource temporarily unavailable) while connecting to upstream ...

And in the browser I got this: ![error](https://cloud.githubusercontent.com/assets/1068973/6812555/0445527c-d270-11e4-9347-cf44155542a8.png)

I don't know if it would keep restarting, I restarted nginx as soon as I saw the problem and fixed the error.

Thanks for the help!

**Comment by FooBarWidget** [comment]
@jonfer Could you post all your Nginx configuration files? Can you als tell me what the owner is of the file config.ru in your application?

**Comment by jonfer** [comment]
@FooBarWidget Looks like upgrading to Phussion Passenger 5.0.5 fixed the problem. Thanks for the help!

**Comment by FooBarWidget** [comment]
Great. :) @allaire is it fixed for you too? Can I close the issue?

**Comment by allaire** [comment]
@FooBarWidget We just updated Passenger to 5.0.6 in our production environment. So far so good. Let me report back tomorrow.

**Comment by allaire** [comment]
@FooBarWidget 

```
  * PID: 17084   Sessions: 75      Processed: 2311    Uptime: 7h 55m 7s
  * PID: 17132   Sessions: 75      Processed: 2621    Uptime: 7h 55m 3s
  * PID: 17166   Sessions: 75      Processed: 5381    Uptime: 7h 54m 59s
  * PID: 17199   Sessions: 74      Processed: 4627    Uptime: 7h 54m 55s
  * PID: 17233   Sessions: 74      Processed: 5504    Uptime: 7h 54m 52s
  * PID: 17257   Sessions: 75      Processed: 3081    Uptime: 7h 54m 48s
  * PID: 17277   Sessions: 75      Processed: 2286    Uptime: 7h 54m 43s
  * PID: 17320   Sessions: 75      Processed: 2228    Uptime: 7h 54m 39s
  * PID: 17373   Sessions: 75      Processed: 3348    Uptime: 7h 54m 34s
  * PID: 17411   Sessions: 73      Processed: 2748    Uptime: 7h 54m 29s
  * PID: 17435   Sessions: 74      Processed: 6786    Uptime: 7h 54m 24s
  * PID: 17457   Sessions: 76      Processed: 2615    Uptime: 7h 54m 19s
  * PID: 17484   Sessions: 75      Processed: 2851    Uptime: 7h 54m 13s
  * PID: 17508   Sessions: 74      Processed: 709     Uptime: 7h 54m 6s
  * PID: 17546   Sessions: 74      Processed: 4105    Uptime: 7h 53m 59s
  * PID: 17575   Sessions: 75      Processed: 3148    Uptime: 7h 53m 55s
  * PID: 17605   Sessions: 73      Processed: 3180    Uptime: 7h 53m 50s
  * PID: 17633   Sessions: 74      Processed: 3051    Uptime: 7h 53m 46s
  * PID: 17659   Sessions: 74      Processed: 4498    Uptime: 7h 53m 43s
  * PID: 17679   Sessions: 73      Processed: 5405    Uptime: 7h 53m 38s
  * PID: 17701   Sessions: 74      Processed: 3008    Uptime: 7h 53m 35s
  * PID: 17723   Sessions: 73      Processed: 4107    Uptime: 7h 53m 30s
  * PID: 17768   Sessions: 74      Processed: 4059    Uptime: 7h 53m 26s
  * PID: 17795   Sessions: 78      Processed: 3798    Uptime: 7h 53m 21s
  * PID: 17823   Sessions: 74      Processed: 3171    Uptime: 7h 53m 17s
  * PID: 17847   Sessions: 74      Processed: 5107    Uptime: 7h 53m 13s
  * PID: 32756   Sessions: 75      Processed: 2692    Uptime: 7h 52m 1s
  * PID: 674     Sessions: 74      Processed: 2376    Uptime: 7h 51m 55s
  * PID: 3321    Sessions: 74      Processed: 3310    Uptime: 7h 51m 50s
  * PID: 5171    Sessions: 74      Processed: 3903    Uptime: 7h 51m 44s
  * PID: 5497    Sessions: 74      Processed: 3424    Uptime: 7h 51m 39s
  * PID: 5788    Sessions: 74      Processed: 2024    Uptime: 7h 51m 35s
```

Sessions never seem to clean out when somebody disconnect, here's our Nginx config:

```
  passenger_sticky_sessions on;
  passenger_sticky_sessions_cookie_name "cc-route";
  passenger_friendly_error_pages off;
  passenger_env_var MONGO_URL <%= fetch(:mongo_url) %>;
  <% if(fetch(:oplog_url)) %>
  passenger_env_var MONGO_OPLOG_URL <%= fetch(:oplog_url) %>;
  <% end %>
  passenger_env_var MAIL_URL <%= fetch(:mail_url) %>;
  passenger_env_var ROOT_URL <%= fetch(:root_url) %>;
  passenger_env_var PORT <%= fetch(:port) %>;
  passenger_env_var HTTP_X_FORWARDED_PROTO https;
  passenger_app_type node;
  passenger_startup_file build/bundle/main.js;
  passenger_min_instances <%= fetch(:min_instances) %>;
```

Any ideas? Is this related?

**Comment by allaire** [comment]
Also, why do we have to always delete our gem versions of passenger to be able to use `passenger-status` again? Is it because going from 4.x to 5.x is a major release, and we can't have both gems installed?

Thanks!

**Comment by OnixGH** [comment]
@allaire is the original problem of "Meteor app kept restarting" solved? What you're reporting seems like a different issue so we'd like to close this one.

**Comment by OnixGH** [comment]
For your other report, if it's still occurring, please open another issue and paste the full output of the commands that @FooBarWidget pasted so we can help.
 1. The output of `passenger-status --show=requests`.
 2. The output of `passenger-status` (without the `--show=requests` part).

**Comment by allaire** [comment]
@OnixGH Yes, Meteor app stopped restarting, so this can be considered resolved.

**Comment by allaire** [comment]
@OnixGH @FooBarWidget We recently had a similar situation with Passenger (Meteor app workers kept restarting) with with a huge stack (I saw ulimit stuff somewhere), we upgraded from 5.0.6 to 5.0.15 and now it seems to have fixed it, anything you changed that could have fix it between these two versions?

Thanks!
