### ISSUE TITLE
Apache processes sometimes lockup with passenger 5.0.2

### ISSUE THREAD

**Issue by tomhughes** [phusion/passenger#1425]
You're probably going to have trouble reproducing this, but hopefully you can at least give me some clues what more information to gather...

Using passenger 5.0.2 with apache 2.4.7 and the event mpm I am seeing that occasionally an apache process will lockup, not accepting any more connections but exiting either. I think it probably happens when a process tries to exit because it has hit one of it's limits but I can't be completely sure. The net result is that the number of available servers gradually drops until there is nothing left:

![apache_processes-day](https://cloud.githubusercontent.com/assets/147741/6601909/4b12555c-c810-11e4-861c-d5308550b64a.png)

After it happened twice I switched back to passenger 4 and everything was fine again...

Working on a test server I established that when it happens there are, in addition to the idle worker threads, three threads present. The first is the main thread:

```
Thread 1 (Thread 0x7fd308c0e780 (LWP 2018)):
#0 0x00007fd30816566b in pthread_join (threadid=140543728080640, thread_return=0x7fff0c3d8a38) at pthread_join.c:92
#1 0x00007fd30839f5fd in apr_thread_join () from /usr/lib/x86_64-linux-gnu/libapr-1.so.0
#2 0x00007fd30467cde7 in join_workers (listener=0x7fd3044fc448, threads=threads@entry=0x7fd30a485a00) at event.c:2053
#3 0x00007fd30467d13f in child_main (child_num_arg=child_num_arg@entry=0) at event.c:2242
#4 0x00007fd3046818c2 in make_child (s=0x7fd308bfade0, slot=0) at event.c:2299
#5 0x00007fd30468208d in perform_idle_server_maintenance () at event.c:2496
#6 server_main_loop (remaining_children_to_start=0) at event.c:2624
#7 event_run (_pconf=<optimized out>, plog=<optimized out>, s=<optimized out>) at event.c:2683
#8 0x00007fd308c726de in ap_run_mpm (pconf=0x7fd308c28028, plog=0x7fd308bf6028, s=0x7fd308bfade0) at mpm_common.c:96
#9 0x00007fd308c6be76 in main (argc=3, argv=0x7fff0c3d8eb8) at main.c:777
``` 

That is waiting for the listener thread (which ha been told to exit and is no longer accepting connections) to do so. The listener thread is polling for something:

```
Thread 2 (Thread 0x7fd2e2fcd700 (LWP 2070)):
#0 0x00007fd307e91b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1 0x00007fd30839ae87 in ?? () from /usr/lib/x86_64-linux-gnu/libapr-1.so.0
#2 0x00007fd30467ff7c in listener_thread (thd=0x7fd3044fc448, dummy=<optimized out>) at event.c:1460
#3 0x00007fd308164182 in start_thread (arg=0x7fd2e2fcd700) at pthread_create.c:312
#4 0x00007fd307e9147d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

What it is waiting for is hard to establish as there doesn't seem to be any way to inspect the contents of an epoll set externally.

Finally there is the passenger thread, which is blocked in `read` on a unix domain socket:

```
Thread 27 (Thread 0x7fd2ef7e6700 (LWP 2045)):
#0 0x00007fd30816b3bd in read () at ../sysdeps/unix/syscall-template.S:81
#1 0x00007fd3041b0d20 in ?? () from /usr/lib/apache2/modules/mod_passenger.so
#2 0x00007fd308c7732e in ap_content_length_filter (f=0x7fd2e02a8778, b=0x7fd2e02ab8a0) at protocol.c:1338
#3 0x00007fd308ca5f6f in ap_byterange_filter (f=0x7fd2e02a8750, bb=0x7fd2e02ab8a0) at byterange_filter.c:496
#4 0x00007fd304ea3479 in filter_harness (f=0x7fd3002deaf0, bb=0x7fd2e02ab8a0) at mod_filter.c:314
#5 0x00007fd3041bd72c in ?? () from /usr/lib/apache2/modules/mod_passenger.so
#6 0x00007fd3041c1d9f in ?? () from /usr/lib/apache2/modules/mod_passenger.so
#7 0x00007fd3041b20b5 in ?? () from /usr/lib/apache2/modules/mod_passenger.so
#8 0x00007fd308c8b830 in ap_run_handler (r=0x7fd2e02a70a0) at config.c:169
#9 0x00007fd308c8bd79 in ap_invoke_handler (r=r@entry=0x7fd2e02a70a0) at config.c:439
#10 0x00007fd308ca133a in ap_process_async_request (r=0x7fd2e02a70a0) at http_request.c:317
#11 0x00007fd308c9e170 in ap_process_http_async_connection (c=0x7fd2e02ab330) at http_core.c:143
#12 ap_process_http_connection (c=0x7fd2e02ab330) at http_core.c:228
#13 0x00007fd308c94e70 in ap_run_process_connection (c=0x7fd2e02ab330) at connection.c:41
#14 0x00007fd30467f81b in process_socket (my_thread_num=25, my_child_num=<optimized out>, cs=0x7fd2e02ab2b8, sock=<optimized out>, p=<optimized out>, thd=<optimized out>) at event.c:970
#15 worker_thread (thd=<optimized out>, dummy=<optimized out>) at event.c:1815
#16 0x00007fd308164182 in start_thread (arg=0x7fd2ef7e6700) at pthread_create.c:312
#17 0x00007fd307e9147d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Unfortunately as `mod_passenger.so` has been stripped and there is no dbg package for it we are limited in what we can see about what it is doing.

The other end of the unix socket it is reading from is the `PassengerAgent` process.

I'm seeing this with at least two different applications, so I suspect it's not being triggered by anything the application as doing.

Hopefully this is enough to give you some ideas, or at least to suggest other things I can look at...

**Comment by FooBarWidget** [comment]
Thanks for reporting this. I think that whatever is going on is caused by something within PassengerAgent, not within the Apache module.

Earlier this week we fixed a bug that *might* be related to your issue.

**Comment by FooBarWidget** [comment]
Version 5.0.4 has been released. I believe the bug you're reporting has been fixed, but there's also a chance that the issue you're running into is a different one. Could you give 5.0.4 a try? And if you still run into the problem, could you gather some analysis data as follows?

 1. Please save the output of `passenger-status --show=requests`.
 2. Please save the output of `passenger-status` (without the `--show=requests` part).
 3. If in the passenger-status output you saw one or more processes with a session count larger than 0, please send SIGQUIT to one of those processes, and save the backtrace that has been dumped to the web server error log.

**Comment by tomhughes** [comment]
I've updated a couple of our secondary servers - it should be clear within a day or so if that is working.

**Comment by tomhughes** [comment]
Looks like it is still happening I'm afraid. This time there are actually two passenger threads in the apache process that seem to be stuck in that read call.

I've put the requested information at https://gist.github.com/tomhughes/5cf3721baa0ffe93b622 but at first glance it doesn't look like the passenger process I dump the stack for is stuck in any way.

**Comment by FooBarWidget** [comment]
Indeed, it looks like PassengerAgent is fine. Maybe it is in mod_passenger after all, possibly something specific to event MPM. The investigation continues.

**Comment by FooBarWidget** [comment]
@tomhughes Does one of your applications happen to do anything with WebSockets?

**Comment by tomhughes** [comment]
The production servers certainly don't, and neither as far as I know does the taginfo server which is also seeing the problem. I doubt anything on the dev server (where today's traces came from) is using them either.

**Comment by FooBarWidget** [comment]
I think what is happening here is that the Apache module doesn't always correctly setup a non-persistent connection with the PassengerAgent. As a result, PassengerAgent never closes the connection while the Apache module keeps waiting forever for the connection to be closed.

In `constructRequestHeaders` in ext/apache2/Hooks.cpp, the Apache module tries to setup a non-persistent connection by setting the right Connection header. The value depends on what the HTTP client's connection header is. Maybe the checks there are insufficient. I'll find a way to improve this.

**Comment by FooBarWidget** [comment]
@tomhughes I think I've fixed this problem, but I need your confirmation on this. I've pushed the fix to the `GH1425` branch. Could you give this branch a try?

**Comment by tomhughes** [comment]
Not easily, as we're currently using the packaged Ubuntu versions...

How would I go about trying out the branch? Obviously I know how to check it out, and I can probably figure out how to build the apache module and persuade apache to use it but presumably I also need to get the ruby bits in the right place so it will use them?

**Comment by FooBarWidget** [comment]
You can try it as follows. First, checkout the git repository somewhere and switch to the branch:

    cd ~/somewhere
    git clone git://github.com/phusion/passenger.git
    cd passenger
    git checkout GH1425

Next, compile the Apache module using the installer. Note: the "installer" doesn't actually install anything; it only checks for dependencies, compiles things and tell you what to do next.

    ./bin/passenger-install-apache2-module

At the end, the installer will tell you to paste a config snippet into the Apache config file. Do not do that. Instead, take note of the filename in the `LoadModule` directive in the config snippet. It probably says something like `/somewhere/passenger/buildout/apache/mod_passenger.so`.

Next, open the file /etc/apache2/mods-enabled/passenger.load. Find the `LoadModule` directive, comment it out, and put a new `LoadModule` directive in there that references the filename as you noted above. For example:

    # Commented out: original line
    # LoadModule passenger_module /usr/lib/apache2/mod_passenger.so

    # Newly inserted:
    LoadModule passenger_module /somewhere/passenger/buildout/apache/mod_passenger.so

Stop and start Apache. You literally have to stop and start. A "restart" is not enough.

    sudo apachectl stop
    sudo apachectl start

You are now ready. If your servers have been stable for a few days then we can assume the bug is fixed.

Here's how you can undo the changes:

1. Edit /etc/apache2/mods-enabled/passenger.load and restore it to its original state.
2. Stop and start Apache.
3. Remove /somewhere/passenger.

**Comment by tomhughes** [comment]
So it's enough just to use the new module then? That's compiling now so I will install it shortly...

**Comment by FooBarWidget** [comment]
Yes.

**Comment by tomhughes** [comment]
I've had that branch running the dev server for about 24 hours now, on the taginfo machine for about 18 and on one of the production web servers for about 5 hours.

None have shown any problems, so I think we can say you've managed to nail it.

**Comment by FooBarWidget** [comment]
Great. :)
