### ISSUE TITLE
Passenger 5.0.4 + Apache + Rails 4.2.0 crash

### ISSUE THREAD

**Issue by aboltart** [phusion/passenger#1431]
passenger-status
```
Version : 5.0.4
Date    : 2015-03-13 10:49:20 +0200
Instance: hhHNC7pu (Apache/2.2.3 (Red Hat) Phusion_Passenger/5.0.4)
````

Here you will find full stack trace https://gist.github.com/aboltart/7f254dc7ec33d9d39ec5

**Comment by FooBarWidget** [comment]
Thanks for the report. Are you using Union Station?

**Comment by aboltart** [comment]
No I am not using Union Station.
If you need some more info please send some commands or file names which output is needed to solve issue

**Comment by aboltart** [comment]
With passenger ```4.0.53``` all is fine

**Comment by tirdadc** [comment]
Same issue, can't get it to work with Rails 4.2 and I get this error:

`[Fri Mar 13 08:21:35 2015] [notice] child pid 2692 exit signal Segmentation fault (11)`

```
Version : 5.0.4
Date    : 2015-03-13 08:20:31 -0400
Instance: GIxDOWSu (Apache/2.2.22 (Ubuntu) PHP/5.3.10-1ubuntu3.15 with Suhosin-Patch Phusion_Passenger/5.0.4)
```
I'll gladly post a stack trace if you tell me how to get it.

**Comment by aboltart** [comment]
@tirdadc 

You can set

```ruby
PassengerLogLevel 2
PassengerDebugLogFile path_to_logfile
```

after that is needed to stop & start apache. restart is not enough

More info https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#_logging_and_debugging_options

**Comment by FooBarWidget** [comment]
I haven't found the root cause for this yet, but scheduling it for 5.0.5.

**Comment by FooBarWidget** [comment]
Should be fixed now.

**Comment by TeamRainless** [comment]
Still not working for me. And I believe I've added the latest version of passenger... I just reinstalled and compiled the whole module right now.

**Comment by FooBarWidget** [comment]
@TeamRainless The fix is in the git repository and hasn't been released yet. Please wait for 5.0.5.

**Comment by TeamRainless** [comment]
Ha! That kind of leaves me in a hell of a jam. Can you tell me how I can install the ubuntu apache module for 4.0.53 now that I'm on 5.0.4?

**Comment by FooBarWidget** [comment]
If you want to downgrade to 4.x, use this: https://blog.phusion.nl/2015/03/12/passenger-5-0-4/

**Comment by FooBarWidget** [comment]
If you want to downgrade to 4.x, use this: https://blog.phusion.nl/2015/03/08/passenger-4-apt-repository-now-available/

**Comment by FooBarWidget** [comment]
@TeamRainless 5.0.5 was released earlier this week.

**Comment by TeamRainless** [comment]
Thanks. Guess it's time to upgrade.

**Comment by tirdadc** [comment]
Works fine with 5.0.6. A proper stop / start is needed, not just a graceful or restart.

**Comment by TeamRainless** [comment]
I actually got it to work with 5.0.4 with gem 'active_attr'. Once I added
that it worked just fine.
