### ISSUE TITLE
HTTP 403 and 404 errors on Heroku

### ISSUE THREAD

**Issue by rassom** [phusion/passenger#1842]
## Issue report

I've just found out that there's been 403 and 404 errors in my logs on Heroku every day for a long time.

Using RubyGems + Gemfile: Rails 4.2.6, Ruby 2.3.1p112, Passenger v5.0.29.

403:    
````
host app web.1 - App 89 stderr: Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.29/rubyext-ruby-2.3.1-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
````

404:    
````
host app web.1 - App 89 stderr: Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.29/rubyext-ruby-2.3.1-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
````

How do I avoid these errors?

Thanks :-)

PS. Log entries attached as CSV.

**Comment by FooBarWidget** [comment]
This was a temporary problem with our file server that lasted a couple of hours yesterday. You couldn't have had these errors "every day for a long time" -- they should only have appeared since yesterday. The file server problem is fixed now so your errors should be gone by now.

**Comment by rassom** [comment]
The errors *do* go a while back and occured again this morning, so it's not fixed. Please re-open the issue.

From this mornings log:
````
2016-07-17T23:23:47.277972+00:00 host app web.1 - App 89 stderr: Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.29/rubyext-ruby-2.3.1-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
````

**Comment by FooBarWidget** [comment]
Oops, you're right, I looked at the URL wrongly and this is a different issue from what I thought it was.

But this issue is about binaries for the Ruby 2.3.1 native extension. We don't supply a precompiled binary for that at this time. Nevertheless, this is a harmless warning: Passenger will work fine even if it cannot download the precompiled binary. It will either compile it locally or use fallback code.
