### ISSUE TITLE
Hash Sum mismatch error on apt-update

### ISSUE THREAD

**Issue by ErikMcDonald** [phusion/passenger#1989]
**Question 1: What is the problem?**
Your answer:

Noticed these failures on apt-get update:
W: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer:
N/A

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:
Ubuntu 14.04

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[X] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:
Ruby 2.3.4

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:
No

**Question 7: Anything else about your setup that we should know?**

Your answer:

---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**Comment by OnixGH** [comment]
Known issue, being worked on.

**Comment by karthiknamburu** [comment]
Im having a similar issue.is there any workaround available for this?

**Comment by CamJN** [comment]
Wait a few more minutes, sorry for the hassle.

**Comment by CamJN** [comment]
Ok the issues should be fixed, you may need to run `sudo apt-get clean ` before trying to update or install again.

**Comment by ErikMcDonald** [comment]
I ran sudo apt-get clean, but I am still getting the same failures as before:

W: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by excid3** [comment]
I'm not quite sure if this is related, but installing passenger and nginx-extras does not work at the moment. Seems to have cropped up around the same time.

```bash
$ sudo apt-get install -y nginx-extras passenger
Reading package lists... Done
Building dependency tree
Reading state information... Done
passenger is already the newest version (1:5.1.9-1~xenial1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx-extras : Depends: nginx-common (= 1:1.12.1-8.5.1.9~xenial1) but 1:1.12.1-8.5.1.10~xenial1 is to be installed
                Recommends: passenger (< 5.1.10) but 1:5.1.9-1~xenial1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by FooBarWidget** [comment]
We performed a new release an hour ago. We made sure we cleared the proxy cache after a small delay, but looks like that wasn't enough. Anyway I've re-cleared the proxy cache now, so it should work.

**Comment by excid3** [comment]
@FooBarWidget That seems to have fixed it. 👍

**Comment by ErikMcDonald** [comment]
It is working on my end as well.  Thanks!

**Comment by karthiknamburu** [comment]
Thank you.Its working now.
