### ISSUE TITLE
Missing passenger.conf when installing on Ubuntu 18.04 Bionic Beaver

### ISSUE THREAD

**Issue by taq** [phusion/passenger#2076]
Hi.

I used to install Nginx and Passenger on Ubuntu, after adding the keys and the required packages, like this:

```
apt install -y nginx-extras passenger
```
Today I just repeated all the steps I use to do but now on Ubuntu 18.04 Bionic Beaver server. When I tried to include the Passenger module on the Nginx configuration, with

```
include /etc/nginx/passenger.conf;
```
I noticed that this file does not exists. I searched on the package files and

```
$ dpkg-query -L passenger | grep "\.conf"
/usr/share/passenger/templates/error_renderer/with_details/webpack.config.js
/usr/share/passenger/templates/error_renderer/without_details/webpack.config.js
```
then I run the same command on a Ubuntu 16.04 server and

```
$  dpkg-query -L passenger | grep "\.conf"
```

Ouch! Nothing! Then I searched on the Ubuntu 16.04 server which package who installed `/etc/nginx/passenger.conf` and 

```
$ dpkg -S /etc/nginx/passenger.conf 
nginx-common: /etc/nginx/passenger.conf

$ dpkg-query -L nginx-common | grep "passenger\.conf"
/etc/nginx/passenger.conf
```
So, the `nginx-common` package is who provides the `/etc/nginx/passenger.conf`. I checked on the 18.04 server and got nothing: 

```
$ dpkg-query -L nginx-common | grep "passenger\.conf"
```
Then I checked [the Ubuntu packages list](https://packages.ubuntu.com/bionic/nginx) for some package that could provide `/etc/nginx/passenger.conf` back and [just found it on a Apache package](https://packages.ubuntu.com/search?searchon=contents&keywords=passenger.conf&mode=exactfilename&suite=bionic&arch=any).

So, while not sure if a Passenger package issue, do you guys have an idea where `passenger.conf` is on Ubuntu 18.04 server?

Thanks!

**Comment by taq** [comment]
Hey Hongli! Last time we met was on the Brazilian RubyConf back on 2013! :-)

**Comment by CamJN** [comment]
On Bionic, the nginx module is a dynamically loaded nginx module, so we do not use the nginx-extras module. Try following the instructions here: https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic/. I had a `50-mod-http-passenger.conf` after going through the procedure.

**Comment by taq** [comment]
Voilá, @CamJN !!!

```
$ ls -lah /etc/nginx/modules-enabled/50-mod-http-passenger.conf
/etc/nginx/modules-enabled/50-mod-http-passenger.conf -> /usr/share/nginx/modules-available/mod-http-passenger.load

$ cat /etc/nginx/modules-enabled/50-mod-http-passenger.conf
load_module /usr/lib/nginx/modules/ngx_http_passenger_module.so;

$ cat /etc/nginx/conf.d/mod-http-passenger.conf
### Begin automatically installed Phusion Passenger config snippet ###
passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
passenger_ruby /usr/bin/passenger_free_ruby;
### End automatically installed Phusion Passenger config snippet ###
```

Weird stuff, the first time I tried to restart Nginx it complained about the `passenger_root` clause:

```
nginx: [emerg] unknown directive "passenger_root" in /etc/nginx/conf.d/mod-http-passenger.conf:2
```

and the file contents were empty after that!

```
$  cat /usr/share/nginx/modules-available/mod-http-passenger.load
```

Then I removed `libnginx-mod-http-passenger` and installed it again, seems to be working now:

```
Everything looks good. :-)
```

Thanks for your help, guys!

**Comment by FooBarWidget** [comment]
Hello @taq, nice seeing you again. :) Good to see that your issue has been solved.

**Comment by kwunyeung** [comment]
I have this same issue after upgrading from 16.04LTS. I have reinstalled nginx, passenger, libnginx-mod-http-passenger and checked every conf file but still not working.

**Comment by rizqirizqi** [comment]
I installed `libnginx-mod-http-passenger` and it suddenly works.

**Comment by CamJN** [comment]
@kwunyeung please open a separate issue and provide all of the requested information, and what steps you took when installing. Thank you.

**Comment by chuchuva** [comment]
Reinstalling libnginx-mod-http-passenger helped

    sudo apt install -y libnginx-mod-http-passenger

**Comment by FeanorsCurse** [comment]
Just ran into the same problem - still an issue.

**Comment by alilland** [comment]
Still an issue

followed the steps found here [https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic](https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic/)

nginx works fine with its defaults, but as soon as i try to add any passenger specific details it throws error messages

```txt
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name _;

        location / {
                passenger_enabled       on;
                passenger_ruby          /home/myuser/.rvm/gems/ruby-2.6.5/wrappers/ruby;
                passenger_base_uri      /;
                passenger_app_root      /var/www/pathtorubyapp;
                passenger_document_root /var/www/pathtorubyapp/public;
        }
}
```

I did have to manually add the `/etc/nginx/conf.d/mod-http-passenger.conf` file

after failing with the official docs, I found this blog post here, and failed with this one too [https://calvin.my/posts/setting-up-nginx-and-passenger-on-ubuntu-18-04](https://calvin.my/posts/setting-up-nginx-and-passenger-on-ubuntu-18-04)
