### ISSUE TITLE
Error in `Passenger core': malloc(): memory corruption

### ISSUE THREAD

**Issue by HimanshuM** [phusion/passenger#2089]
Open source Passenger 5.1.2/Nginx, installed through Rubygems with RVM
Linux 4.4.0-128-generic #154-Ubuntu SMP
Ruby 2.1.8
Rails 4

While restarting Nginx, Passenger core seems to be reluctant to start. It gets stuck in a loop of attempting to restart the core. After maybe, an hour or so, the Passenger is up and stable. But as soon as I restart Nginx, the process repeats.
Tried looking for it over the internet, could not find the exact same issue anywhere.

This started since today morning, apparently randomly. And restarting the server is not helping either.
I have some 1200+ crash dumps on my server by now...

I have attached the log, logged at level 7. Hope it helps figuring out my issue...
[passenger-crash-log.1528827885.txt](https://github.com/phusion/passenger/files/2095360/passenger-crash-log.1528827885.txt)

**Comment by sixfeetover** [comment]
This is happening for us as well, across multiple different servers. Our stack trace implies it is related to the phone home for security updates as it fails establishing a connection to 159.69.16.82, which appears to be Passenger's security check service. Our log looks effectively the same as @HimanshuM's.

**Comment by CamJN** [comment]
This is likely due to an issue fixed in 5.1.5 where once enough security advisories had built up and the total length of the response from the security update check server exceeded ~500B then Passenger would crash. You can update to the latest version of Passenger to receive this fix, or disable the security update checker if you aren't going to use it.

**Comment by sixfeetover** [comment]
Most of our instances are using 5.1.5, including the ones experiencing this issue. However, we will go ahead and disable it and work on deploying 5.3.

**Comment by kotcity** [comment]
There's going to be a lot of crashing Passengers out in the wild. Any chances of keeping the security info short to avoid crashing and then supply a new URL for new Passenger versions?

**Comment by HimanshuM** [comment]
Hi @CamJN , thank you for your quick response. Disabling the security update check fixed the problem for now. I guess, we needed to a push to perform the upgrade to a newer version :)

**Comment by kotcity** [comment]
@CamJN is there the possibility of having the securitycheck server NOT send large output to these older affected versions? not everyone has the ability to upgrade at the drop of a hat.

**Comment by shanedroid** [comment]
Can confirm we were bit by this as well running on `5.1.3` installed through Rubygems with RVM.

```
Linux 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
Apache/2.4.7 (Ubuntu)
Passanger 5.1.3 
```

This could have been messy for us had we not caught it in time - thankfully [disabling the security update](https://www.phusionpassenger.com/library/config/apache/reference/#passengerdisablesecurityupdatecheck) as per @CamJN worked for now and we will be updating to `5.1.3`

Agree with @sixfeetover that this issue should not be left closed unless the default setting is changed or at that docs can be updated to reflect that in order to leave security updated enabled you must be running `~> 5.1.5` to hopefully help others from getting hosed by this.

**Comment by bongole** [comment]
Hi, same error happened on passenger-5.1.1.

May be this commit fixed the error.
https://github.com/phusion/passenger/commit/986776dd7e54a95cc37b776f316bc095c54c37a5

**Comment by rakuhei** [comment]
Hi , I see  the same bug.
I want to know is the occurrence reason.
---------
Apache/2.4.6
passenger 5.1.2
CentOS Linux release 7.3.1611
ruby 2.3.3p222
---------

I found the securitycheck URL on the SecurityUpdateChecker.h
----------
$cat SecurityUpdateChecker.h

#define CHECK_HOST_DEFAULT "securitycheck.phusionpassenger.com" 
#define CHECK_URL_DEFAULT "https://" CHECK_HOST_DEFAULT ":443/v1/check.json"
----------

And,check the URL.
----------
Command:
curl -k https://securitycheck.phusionpassenger.com:443/v1/check.json

Response:
This is not the way to access the security update check. For more information, see: <a href='https://www.phusionpassenger.com/library/indepth/security_update_check.html'>https://www.phusionpassenger.com/library/indepth/security_update_check.html</a>.
----------
It's not JSON response.
I think this bug has been caused by changing the response.
It's so right ?

**Comment by Insood** [comment]
+1 - another 2 broken servers on Passenger 5.1.2

Will be updating to 5.3.2 tonight (as I should've... a long time ago)

**Comment by GUI** [comment]
One small note, but I think this was actually fixed in 5.1.6, not 5.1.5 as earlier mentioned: https://github.com/phusion/passenger/blob/320d397705046d46c777cf315f1a8ec87ec55189/CHANGELOG#L1-L4

So I just thought that might help clear up confusion for people that were already running 5.1.5 and also hitting this.

**Comment by FooBarWidget** [comment]
We've now updated the security check server to send a custom message for Passenger < 5.1.6 so that they don't crash. Of course, people should still upgrade in order to get the latest security fixes.

**Comment by aaronlifton2** [comment]
@FooBarWidget  Still crashing. Doesn't seem like that worked. Had to disable security check

**Comment by tadams42** [comment]
I can confirm this on Ruby 2.2, Passenger 5.1.4. Upgrade to Passenger 5.2.3 solved it.

It was a pretty weird issue since our servers that hadn't been touched for months started segfaulting one after another. 

Man I'm glad to have found this issue because we were unable to figure out root cause and that was quite demoralizing.

**Comment by CamJN** [comment]
Closing since this should be done.
